import Image from "next/image";
import x from "../../../assests/X_logo_2023_(white).png";
import Google from "../../../assests/google.png";
import { FormEvent, useState } from "react";
import { signInWithEmailAndPassword } from "firebase/auth";
import { auth } from "@/firebase/init";
import { useRouter } from "next/router";
import Apple from "../../../assests/apple.png";

import Head from "next/head";

import { TextField } from "@mui/material";
import { XMarkIcon } from "@heroicons/react/24/outline";

type Props = {};
function SigninUser({}: Props) {
  const router = useRouter();

  const [proceedToCreateProfile, setProceedtoCreateProfile] =
    useState<boolean>(false);
  const [wrongPassword, setWrongPassword] = useState<boolean>(false);
  const [wrongEmail, setWrongEmail] = useState<boolean>(false);
  const [Email, setEmail] = useState<string>();
  const [Password, setPassword] = useState<string>();
  const [signInModal, setSignInModal] = useState<boolean>(false);

  function loginUser(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();

    signInWithEmailAndPassword(auth, Email!, Password!)
      .then((userCredential) => {
        router.push("/");
      })
      .catch((error) => {
        if (error.code === "auth/wrong-password") {
          setWrongPassword(true);
        }
        if (error.code === "auth/user-not-found") {
          setWrongEmail(true);
        }
      });
  }

  function changeLoginModalState() {
    setSignInModal(!signInModal);
    const element = document.getElementById("mainPage");
    if (signInModal == false) {
      element?.classList.add("openModal");
    } else {
      element?.classList.remove("openModal");
    }
  }

  return (
    <>
      <section
        id="mainPage"
        className=" p-8 bg-black w-full  md:h-[100vh] md:overflow-hidden m:auto text-white "
      >
        <Head>
          <title>Log In</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div
          id="secondary"
          className="  space-y-6  md:space-y-0  md:flex md:items-center md:space-x-4 md:h-full  md:justify-center"
        >
          <div className=" md:w-[50%] lg:p-20  xl:p-32">
            <Image src={x} alt="X logo" className=" w-14 md:w-full" />
          </div>
          <div className=" md:w-[50%] lg:w-[80%] xl:w-[50%] space-y-4 lg:p-20 xl:p-32">
            <h1 className=" font-bold text-5xl lg:text-6xl">Happening now</h1>
            <p className=" font-bold text-2xl lg:text-3xl">Join today.</p>
            <div className=" space-y-6 ">
              <button
                disabled
                className=" w-full bg-white flex justify-center items-center py-3 rounded-full space-x-3 "
              >
                <Image src={Google} alt="google" className=" w-6" />
                <span className=" text-gray-500 text-sm font-semibold">
                  Sign up with Google
                </span>
              </button>
              <button
                disabled
                className=" w-full bg-white flex justify-center items-center py-3 rounded-full space-x-3 "
              >
                <Image src={Apple} alt="google" className=" w-6" />
                <span className=" text-gray-500 text-sm font-semibold">
                  Sign up with Apple
                </span>
              </button>
              <div className=" flex items-center ">
                <div className=" w-full h-[0.5px] border"></div>
                <p className=" mx-2">or</p>
                <div className=" w-full h-[0.5px] border"></div>
              </div>
              <div className=" space-y-2">
                <button
                  onClick={() => router.push("/signup")}
                  className=" w-full bg-twitter cursor-pointer text-white px-3 py-2 font-semibold rounded-full"
                >
                  Create account{" "}
                </button>
                <p className=" text-[12px]   text-gray-400">
                  By signing up, you agree to the <span> Terms of Service</span>{" "}
                  and
                  <span className=" text-twitter">Privacy Policy</span>,
                  including <span className="  text-twitter">Cookie Use. </span>
                </p>
              </div>
              <div className=" space-y-3 pt-4">
                <h3 className=" font-semibold text-xl">
                  Already have an account?
                </h3>
                <button
                  onClick={changeLoginModalState}
                  className="  border  border-gray-700 text-twitter font-semibold w-full p-2 rounded-full"
                >
                  {" "}
                  Sign in
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* SIGN IN MODAL */}
      {signInModal && (
        <div className=" absolute w-full h-[100vh]  bg-black  text-white top-0  p-6 md:w-[60%] md:h-[60%] md:top-1/2 md:left-1/2 md:-translate-x-1/2 md:-translate-y-1/2 md:rounded-lg  lg:p-10  lg:h-auto lg:w-1/2  xl:w-1/3 ">
          <XMarkIcon
            onClick={changeLoginModalState}
            className=" w-8 text-white absolute  top-4 left-4"
          />
          <div className=" flex justify-center">
            <Image src={x} alt="x logo" className="w-8 " />
          </div>
          <div className="  space-y-4 flex flex-col justify-center h-full ">
            <p className=" font-bold text-2xl"> Sign in to X</p>
            <button
              disabled
              className=" w-full bg-white flex justify-center items-center py-3 rounded-full space-x-3 "
            >
              <Image src={Google} alt="google" className=" w-6" />
              <span className=" text-gray-500 text-sm font-semibold">
                Sign in with Google
              </span>
            </button>
            <button
              disabled
              className=" w-full bg-white flex justify-center items-center py-3 rounded-full space-x-3 "
            >
              <Image src={Apple} alt="google" className=" w-6" />
              <span className=" text-gray-500 text-sm font-semibold">
                Sign in with Apple
              </span>
            </button>
            <div className=" flex items-center ">
              <div className=" w-full h-[0.5px] border"></div>
              <p className=" mx-2">or</p>
              <div className=" w-full h-[0.5px] border"></div>
            </div>
            <form
              className=" flex flex-col justify-center"
              onSubmit={loginUser}
            >
              <TextField
                id="outlined-basic"
                label="Email Address"
                required
                type="email"
                variant="outlined"
                sx={{
                  fieldset: { borderColor: "#242424" },
                  input: { color: "white" },
                  label: { color: "#242424" },
                  borderColor: "white",
                  border: { color: "white" },
                }}
                error={wrongEmail}
                onChange={(e) => setEmail(e.target.value)}
                helperText="Incorrect Email Address"
              />
              <TextField
                id="outlined-basic"
                label="Password"
                required
                type="password"
                variant="outlined"
                sx={{
                  fieldset: { borderColor: "#242424" },
                  input: { color: "white" },
                  label: { color: "#242424" },
                  borderColor: "white",
                  border: { color: "white" },
                }}
                error={wrongPassword}
                onChange={(e) => setPassword(e.target.value)}
                helperText="Incorrect Password"
              />
              <div>
                <button className=" w-full h-12 font-semibold rounded-full text-black bg-white">
                  {" "}
                  Log in
                </button>
              </div>
            </form>
            <p className="  text-sm text-gray-500">
              Don&apos;t have an account?{" "}
              <span
                onClick={() => router.push("/signup")}
                className=" text-twitter cursor-pointer"
              >
                Sign up
              </span>
            </p>
          </div>
        </div>
      )}
    </>
  );
}
export default SigninUser;
