import Image from "next/image";
import x from "../../../assests/X_logo_2023_(white).png";
import Google from "../../../assests/google.png";
import { FormEvent, useState } from "react";
import { signInWithEmailAndPassword, signOut } from "firebase/auth";
import { auth } from "@/firebase/init";
import { useRouter } from "next/router";
import Apple from "../../../assests/apple.png";
import { useAppDispatch } from "../../../utils/hooks";
import { login } from "../../../slices/userSlice";

import { user } from "../createprofile";
import Link from "next/link";
import Head from "next/head";
import Stack from "@mui/material/Stack";
import Button from "@mui/material/Button";
import { TextField, makeStyles, withStyles } from "@mui/material";
import { XMarkIcon } from "@heroicons/react/24/outline";
import App from "../_app";
import styled from "styled-components";

type Props = {};
function SigninUser({}: Props) {
  const dispatch = useAppDispatch();
  const router = useRouter();
  const [wrongPassword, setWrongPassword] = useState<boolean>(false);
  const [wrongEmail, setWrongEmail] = useState<boolean>(false);
  const [Email, setEmail] = useState<string>();
  const [Password, setPassword] = useState<string>();
  const [signInModal, setSignInModal] = useState<boolean>(false);
  console.log(Email);
  function loginUser(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();

    signInWithEmailAndPassword(auth, Email!, Password!)
      .then((userCredential) => {
        router.push("/");
      })
      .catch((error) => {
        if (error.code === "auth/wrong-password") {
          setWrongPassword(true);
        }
        if (error.code === "auth/user-not-found") {
          setWrongEmail(true);
        }
      });
  }
  return (
    <>
      <section className=" p-8 bg-black w-full  text-white">
        <Head>
          <title>Log In</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="  space-y-6">
          <div>
            <Image src={x} alt="X logo" className=" w-14" />
          </div>
          <div className="  space-y-6">
            <h1 className=" font-bold text-5xl">Happening now</h1>
            <p className=" font-bold text-2xl">Join today.</p>
            <button className=" w-full bg-white flex justify-center items-center py-3 rounded-full space-x-3 ">
              <Image src={Google} alt="google" className=" w-6" />
              <span className=" text-gray-500 text-sm font-semibold">
                Sign up with Google
              </span>
            </button>
            <button className=" w-full bg-white flex justify-center items-center py-3 rounded-full space-x-3 ">
              <Image src={Apple} alt="google" className=" w-6" />
              <span className=" text-gray-500 text-sm font-semibold">
                Sign up with Apple
              </span>
            </button>
            <div className=" flex items-center ">
              <div className=" w-full h-[0.5px] border"></div>
              <p className=" mx-2">or</p>
              <div className=" w-full h-[0.5px] border"></div>
            </div>
            <div className=" space-y-2">
              <button className=" w-full bg-twitter text-white px-3 py-2 font-semibold rounded-full">
                Create account{" "}
              </button>
              <p className=" text-[12px]   text-gray-400">
                By signing up, you agree to the <span> Terms of Service</span>{" "}
                and
                <span className=" text-twitter">Privacy Policy</span>, including{" "}
                <span className="  text-twitter">Cookie Use. </span>
              </p>
            </div>
            {/* <form onSubmit={loginUser} className="mt-10">
            <h2 className="font-bold text-lg">Login</h2>
            <div className="mt-8 space-y-8">
              <div className=" space-y-1">
                {wrongEmail && (
                  <h3 className="text-red-500 text-sm">Wrong Email Address</h3>
                )}
                <input
                  type="email"
                  required
                  className="border p-3 outline-none w-full"
                  placeholder="Email Address"
                  onChange={(e) => setEmail(e.target.value)}
                ></input>
              </div>
              <div className="">
                {wrongPassword && (
                  <h3 className="text-red-500 text-sm">Incorrect Password</h3>
                )}
                <input
                  minLength={8}
                  required
                  type="password"
                  className="border p-3 outline-none w-full"
                  placeholder="Password"
                  onChange={(e) => setPassword(e.target.value)}
                ></input>
              </div>
            </div>

            <button
              type="submit"
              className="text-white  mt-4 bg-black px-4 py-2 rounded-full"
            >
              Log In
            </button>
          </form> */}
          </div>
          <div className=" space-y-3 pt-4">
            <h3 className=" font-semibold text-xl">Already have an account?</h3>
            <button
              onClick={() => setSignInModal(true)}
              className="  border  border-gray-700 text-twitter font-semibold w-full p-2 rounded-full"
            >
              {" "}
              Sign in
            </button>
          </div>
        </div>
      </section>
      {/* SIGN IN MODAL */}
      <div className=" absolute w-full h-full bg-black  text-white top-0  ">
        <XMarkIcon className=" w-8 text-white absolute  top-0 left-0" />
        <div className="  ">
          <Image src={x} alt="x logo" className="w-8" />
          <p className=" font-bold text-2xl"> Sign in to X</p>
          <button className=" w-full bg-white flex justify-center items-center py-3 rounded-full space-x-3 ">
            <Image src={Google} alt="google" className=" w-6" />
            <span className=" text-gray-500 text-sm font-semibold">
              Sign in with Google
            </span>
          </button>
          <button className=" w-full bg-white flex justify-center items-center py-3 rounded-full space-x-3 ">
            <Image src={Apple} alt="google" className=" w-6" />
            <span className=" text-gray-500 text-sm font-semibold">
              Sign in with Apple
            </span>
          </button>
          <div className=" flex items-center ">
            <div className=" w-full h-[0.5px] border"></div>
            <p className=" mx-2">or</p>
            <div className=" w-full h-[0.5px] border"></div>
          </div>
          <TextField
            id="outlined-basic"
            label="Email Address"
            variant="outlined"
            sx={{
              fieldset: { borderColor: "#242424" },
              input: { color: "white" },
              label: { color: "#242424" },
              borderColor: "white",
              border: { color: "white" },
            }}
            error={wrongPassword}
            onChange={(e) => setEmail(e.target.value)}
            helperText="incorrect entry"
          />
        </div>
      </div>
    </>
  );
}
export default SigninUser;
