import Head from 'next/head'
import Nav from '../../components/Nav'
import Feed from '../../components/Feed'
import { Timeline } from 'react-twitter-widgets'
import { useEffect, useState } from 'react'
import { onAuthStateChanged } from 'firebase/auth'
import { auth } from '@/firebase/init'
import { useRouter } from 'next/router'

export interface user {
  displayName: string;
  email: string;
  photoURL: string;
  uid: string;
}

export default function Home() {
  const router = useRouter();
  const [currentUser, setCurrentUser] = useState<user>();
  
  useEffect(() => {

    onAuthStateChanged(auth, (user) => {
      if (user) {
        setCurrentUser({
          displayName: user.displayName || "",
          email: user.email || "",
          photoURL: user.photoURL || "",
          uid: user.uid || ""
        });
      }
      else {
        router.push('/login')
      }
    })

  }, [])

  console.log(currentUser)
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex'>
      <Nav />
      <Feed/>
      <div className='hidden lg:flex p-4  fixed  right-20'>
        <Timeline  dataSource={{ sourceType: "profile", screenName: "elonmusk" }}
        options={{ width: "400", height: "800" }} />
      </div>
   
     
      

      </main>
 

        
     

      

     
     </>
  )
}
