import Head from "next/head";
import Nav from "../../components/Nav";
import Feed from "../../components/Feed";
import { Timeline } from "react-twitter-widgets";
import { useEffect, useState } from "react";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "@/firebase/init";
import { useRouter } from "next/router";
import { useAppDispatch, useAppSelector } from "../../utils/hooks";
import { login } from "../../slices/userSlice";

export interface user {
  displayName: string;
  email: string;
  photoURL: string;
  uid: string;
}

export default function Home() {
  const router = useRouter();
  const dispatch = useAppDispatch();
  const [currentUser, setCurrentUser] = useState<user>();
  const user = useAppSelector(state => state.user.value)


  useEffect(() => {
    if (currentUser) {
      dispatch(login(currentUser))

    }
  },[currentUser])
  useEffect(() => {

onAuthStateChanged(auth, (userCredential) => {

  if (userCredential) {
    setCurrentUser({
      displayName: userCredential.displayName || "",
      email: userCredential.email || "",
      photoURL: userCredential.photoURL || "",
      uid: userCredential.uid || "",
    });
    
  } else {
    router.push("/login");
  }
});

  

    
  }, []);


  

  

  
  


  return (
    <>
      <Head>
        <title>Tweety</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex">
        <Nav />
        
        <Feed />
        <div className="hidden lg:flex p-4  fixed  right-20">
          <Timeline
            dataSource={{ sourceType: "profile", screenName: "elonmusk" }}
            options={{ width: "400", height: "800" }}
          />
        </div>
      </main>
    </>
  );
}
